# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins

class ServerState:
    ...

class UserState:
    def __new__(cls, public_params:bytes) -> UserState: ...

def get_public_parameters(server_state:ServerState) -> bytes: ...

def sum_as_string(a:builtins.int, b:builtins.int) -> builtins.str:
    r"""
    Formats the sum of two numbers as string.
    """

