# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing

class CredentialError(builtins.Exception):
    r"""
    An authentication error
    """
    ...

class DeserializationFailed(builtins.Exception):
    r"""
    An error trying to deserialize a binary buffer
    """
    ...

class ProtocolError(builtins.Exception):
    r"""
    An error performing the protocol
    """
    ...

class ServerState:
    def __new__(cls) -> ServerState: ...
    @staticmethod
    def from_creds(public_parameters:bytes, secret_key:bytes) -> ServerState:
        r"""
        Create a new server state from binary-serialized public and private keys
        This is meant to be used by the server, so it can store the keys somewhere and recreate the
        state when needed
        """
    def get_secret_key(self) -> bytes: ...
    def get_public_parameters(self) -> bytes: ...
    def handle_registration_request(self, registration_request:bytes) -> bytes: ...
    @staticmethod
    def today() -> builtins.int: ...
    def handle_submit_request(self, nym:bytes, request:bytes, probe_cc:str, probe_asn:str, age_range:list, measurement_count_range:list) -> bytes: ...

class SubmitRequest:
    @property
    def nym(self) -> bytes: ...
    @property
    def request(self) -> bytes: ...

class UserState:
    def __new__(cls, public_params:bytes) -> UserState: ...
    def get_credential(self) -> typing.Optional[bytes]: ...
    def make_registration_request(self) -> bytes: ...
    def handle_registration_response(self, resp:bytes) -> None:
        r"""
        Handle a registration response sent by the server, updating your credentials
        
        Note that this function will only work if you previously called
        `make_registration_request`
        """
    def make_submit_request(self, probe_cc:str, probe_asn:str, emission_date:builtins.int) -> SubmitRequest: ...
    def handle_submit_response(self, response:bytes) -> None:
        r"""
        Handle a submit response sent by the server, updating your credentials
        
        Note that this function will only work if you previously called
        `make_submit_request`
        """

